
_select_data:
 video_types:
  - youtube
  - vimeo
  - embedded
 section_styles:
  - p-5: Padding Standard
  - p-6: Padding Medium
  - p-10: Padding Large
  - m-5: Margin Standard
  - m-6: Margin Medium
  - m-10: Margin Large
  - bg-light: Light Background
  - bg-dark: Dark Background
  - bg-featured: Featured Background
  - bg-white: White Background
 inner_styles:
  - p-5: Padding Standard
  - p-6: Padding Medium
  - p-10: Padding Large
  - m-5: Margin Standard
  - m-6: Margin Medium
  - m-10: Margin Large
  - max-w-screen-md: Capped Width Medium
  - max-w-screen-lg: Capped Width Large
  - max-w-screen-xl: Capped Width XL
  

page_blocks: []
_array_structures:
 page_blocks:
  - label: Text Content
    icon: description
    value:
     _id: text-content
     title: Text Content
     section_styles: 
     inner_styles:
     description_html:

  - label: Image Banner
    icon: photo_camera
    value:
     _id: image-banner
     title: Image Banner
     section_styles: 
     inner_styles:     
     banner_image: 
     heading:
     subheading:

  - label: Call to Action
    icon: article
    value:
     _id: cta
     title: Call to Action
     section_styles: 
     inner_styles:     
     heading: This is a heading
     paragraph: This is a paragraph
     button_url: /
     button_text: Home page

  - label: Gallery
    icon: photo_camera
    value:
     _id: gallery
     title: Gallery
     section_styles: 
     inner_styles:     
     gallery_columns: 
     gallery:
      - column_width: 
        gallery_image:
        aspect_ratio: 
  
  - label: Video
    icon: play_circle
    value:
     _id: video
     title: Video
     section_styles: 
     inner_styles:     
     video_poster:
     video_type:
     youtube_id:
     vimeo_id:
     embedded:
       - video_path:
         file_type: