collections:
 posts:
  output: true
  permalink: /posts/:slug
# This allows the client to manually add their own categories and outputs it into the nav menu. These will output into the _cats folder as a markdown file. You can add descriptions in the front matter if needed. Comment out in nav menu if wanted.
#  cats:
#   output: true 

_select_data:
 video_types:
  - youtube
  - vimeo
  - embedded
 section_styles:
    bg-light: Light Background
    bg-black: Dark Background
    bg-featured: Featured Background
    bg-white: White Background
 inner_styles:
    p-5: Padding Standard
    p-6: Padding Medium
    p-10: Padding Large
    m-5: Margin Standard
    m-6: Margin Medium
    m-10: Margin Large
    max-w-screen-md: Capped Width Medium
    max-w-screen-lg: Capped Width Large
    max-w-screen-xl: Capped Width XL
 image_alignment:
    items-center: Align to Centre
    justify-center: Justify to Centre  
_inputs:
# This allows the client to select multiple categories for posts with the Cloudcannon dropdown
#  cats:
#   type: multi-select
#   options:
#    values: collections.cats

 grid_width:
  type: select
  options:
   values:
    1: 1 Column
    2: 2 Column
    3: 3 Columns
    4: 4 Columns
    5: 5 Columns
    6: 6 Columns
    7: 7 Columns
    8: 8 Columns
    9: 9 Columns
    10: 10 Columns
    11: 11 Columns
    12: 12 Columns
 column_width:
  type: select
  options:
   values:
    1: 1 Column
    2: 2 Columns
    3: 3 Columns
    4: 4 Columns
    5: 5 Columns
    6: 6 Columns
    7: 7 Columns
    8: 8 Columns
    9: 9 Columns
    10: 10 Columns
    11: 11 Columns
    12: 12 Columns
 section_spacing:
  type: select
  options:
   values:
    p-5: Padding Standard
    p-6: Padding Medium
    p-10: Padding Large
    m-5: Margin Standard
    m-6: Margin Medium
    m-10: Margin Large
page_blocks: []
_array_structures:
 page_blocks:
  - label: Text Content
    icon: description
    value:
     _id: text-content
     title: Text Content
     column_width:
     section_styles:
     section_spacing:
     inner_styles:
     description_html:

  - label: Image Banner
    icon: photo_camera
    value:
     _id: image-banner
     title: Image Banner
     section_styles: 
     inner_styles:     
     banner_image: 
     heading:
     subheading:

  - label: Complex Grid
    icon: multiple_stop
    value:
     _id: complex-grid
     title: Side By Side
     section_styles:
     grid_width:
     columns:

  - label: Call to Action
    icon: article
    value:
     _id: cta
     title: Call to Action
     section_styles: 
     inner_styles:     
     heading: This is a heading
     paragraph: This is a paragraph
     button_url: /
     button_text: Home page

  - label: Gallery
    icon: photo_camera
    value:
      _id: gallery
      title: Gallery
      section_styles: 
      inner_styles:     
      gallery_columns: 
      gallery:
        - column_width: 
          gallery_image:
          aspect_ratio: 
  
  - label: Video
    icon: play_circle
    value:
     _id: video
     title: Video
     section_styles: 
     inner_styles:     
     video_poster:
     video_type:
     youtube_id:
     vimeo_id:
     embedded:
       - video_path:
         file_type:

 columns:
  - label: image
    icon: photo_camera
    value:
     _type: image
     image:
     column_width:
  - label: text
    icon: description
    value:
     _type: text
     description_html:
     column_width:
  - label: video
    icon: play_circle
    value:
     _type: video
     video_path:
     column_width: